-- #TODO: Load the data

LOAD DATA LOCAL INFILE 'movies_table.csv' INTO TABLE movie
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'movie_genre_table.csv' INTO TABLE movie_genre
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;